"""Tests for the pre-registered panel -> measured-glyph assignment (blocker B5).

These test the **selection and its enforcement only**.  No test asserts a measured
height, none uses physical data, and none changes a criterion.  Several are design
invariants: the allocation is generated by a closed-form rule, so the balance claims
in `docs/B5_GLYPH_SELECTION.md` are asserted here rather than asserted in prose.
"""
from __future__ import annotations

import io
import os
import shutil
import sys
import tempfile
import unittest

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
sys.path.insert(0, ROOT)
sys.path.insert(0, os.path.join(ROOT, "tools"))

import make_coupons_svg as mc                     # noqa: E402
import make_glyph_selection as mgs                # noqa: E402
import validate_selection as vs                   # noqa: E402

from p0.core import dump_json, load_json          # noqa: E402
from p0.render import glyph_shape_class           # noqa: E402

SELECTION = os.path.join(ROOT, "fixtures", "physical", "coupons",
                         "glyph_selection.json")
GLYPH_MAP = os.path.join(ROOT, "fixtures", "physical", "coupons", "glyph_map.json")


def selection():
    return load_json(SELECTION)


def glyph_map():
    return load_json(GLYPH_MAP)


def panels():
    return mgs.load_panels()


def codes(issues, severity="ERROR"):
    return sorted(i["code"] for i in issues if i["severity"] == severity)


def check(sel=None, manifest=None, gmap=None, reference=None, rederive=True):
    sel = sel if sel is not None else selection()
    return vs.validate(sel, manifest, gmap if gmap is not None else glyph_map(),
                       reference, panels() if rederive else None)


def nominal_runs(sel=None, **over):
    sel = sel or selection()
    runs = []
    for g in sel["glyphs"]:
        r = {"run_id": "%s-A-OP1-R1" % g["panel_id"], "panel_id": g["panel_id"],
             "glyph_label": g["glyph_shape"], "nominal_h_mm": g["nominal_h_mm"],
             "glyph_index": 1, "device": "A", "operator": "OP1", "repeat": "R1",
             "safety_class": "SAFE"}
        r.update(over)
        runs.append(r)
    return {"selection_hash": sel["selection_hash"], "runs": runs}


# ---------------------------------------------------------------------------
# the allocation
# ---------------------------------------------------------------------------

class TestAllocationIsDerived(unittest.TestCase):
    def test_committed_selection_matches_a_fresh_derivation(self):
        self.assertEqual(selection(), mgs.build(panels(), glyph_map()))

    def test_derivation_is_stable_across_calls(self):
        a = mgs.build(panels(), glyph_map())
        b = mgs.build(panels(), glyph_map())
        self.assertEqual(a, b)
        self.assertEqual(a["selection_hash"], b["selection_hash"])

    def test_one_glyph_per_panel_and_all_twenty_panels(self):
        sel = selection()
        self.assertEqual(sel["n_panels"], 20)
        self.assertEqual(len(sel["glyphs"]), 20)
        self.assertEqual(len({g["panel_id"] for g in sel["glyphs"]}), 20)

    def test_every_selected_glyph_resolves_in_the_b3_map(self):
        known = {g["glyph_key"] for g in glyph_map()["glyphs"]}
        for g in selection()["glyphs"]:
            self.assertIn(g["glyph_key"], known)

    def test_every_selected_glyph_is_actually_printed_on_that_panel(self):
        by_id = {p["panel_id"]: p for p in panels()}
        for g in selection()["glyphs"]:
            p = by_id[g["panel_id"]]
            self.assertIn(g["nominal_h_mm"],
                          [float(v) for v in p["nominal_heights_mm"]])
            self.assertIn(g["glyph_shape"], p["shapes"])

    def test_shape_class_agrees_with_the_repository_function(self):
        for g in selection()["glyphs"]:
            self.assertEqual(g["shape_class"],
                             glyph_shape_class(g["glyph_shape"]))

    def test_cli_check_passes_on_the_committed_selection(self):
        buf, old = io.StringIO(), sys.stdout
        sys.stdout = buf
        try:
            self.assertEqual(mgs.main(["--check", SELECTION]), 0)
        finally:
            sys.stdout = old

    def test_cli_check_fails_on_a_tampered_selection(self):
        tmp = tempfile.mkdtemp()
        try:
            sel = selection()
            sel["glyphs"][0]["nominal_h_mm"] = 6.0
            p = os.path.join(tmp, "tampered.json")
            dump_json(p, sel)
            buf, old = io.StringIO(), sys.stdout
            sys.stdout = buf
            try:
                self.assertEqual(mgs.main(["--check", p]), 1)
            finally:
                sys.stdout = old
        finally:
            shutil.rmtree(tmp)


class TestBalanceInvariants(unittest.TestCase):
    """Every claim made in the design write-up, asserted."""

    def setUp(self):
        self.g = selection()["glyphs"]

    def _tally(self, key):
        out = {}
        for g in self.g:
            out[g[key]] = out.get(g[key], 0) + 1
        return out

    def test_each_of_the_five_heights_is_on_exactly_four_panels(self):
        self.assertEqual(self._tally("nominal_h_mm"),
                         {float(h): 4 for h in mc.HEIGHTS})

    def test_each_of_the_four_shapes_is_on_exactly_five_panels(self):
        self.assertEqual(self._tally("glyph_shape"), {s: 5 for s in mc.SHAPES})

    def test_each_of_the_four_fonts_is_on_exactly_five_panels(self):
        self.assertEqual(sorted(self._tally("font").values()), [5, 5, 5, 5])

    def test_both_shape_classes_are_present(self):
        self.assertEqual(self._tally("shape_class"), {"FLAT_TOP": 15, "ROUND": 5})

    def test_height_by_shape_is_a_complete_factorial(self):
        pairs = {(g["nominal_h_mm"], g["glyph_shape"]) for g in self.g}
        self.assertEqual(len(pairs), 20)
        self.assertEqual(len(pairs), len(mc.HEIGHTS) * len(mc.SHAPES))

    def test_font_and_height_are_fully_crossed(self):
        self.assertEqual(len({(g["font"], g["nominal_h_mm"]) for g in self.g}), 20)

    def test_every_font_sees_every_shape(self):
        by_font = {}
        for g in self.g:
            by_font.setdefault(g["font"], set()).add(g["glyph_shape"])
        for font, shapes in by_font.items():
            self.assertEqual(shapes, set(mc.SHAPES), font)

    def test_every_sheet_carries_four_distinct_heights(self):
        by_sheet = {}
        for g in self.g:
            by_sheet.setdefault(g["sheet"], []).append(g["nominal_h_mm"])
        for sheet, hs in by_sheet.items():
            self.assertEqual(len(hs), 4, sheet)
            self.assertEqual(len(set(hs)), 4, sheet)

    def test_the_p2_class_is_populated(self):
        n = sum(1 for g in self.g if g["nominal_h_mm"] == vs.P2_CLASS_MM)
        self.assertEqual(n, 4)
        # 4 panels x 2 devices x 2 operators x 3 repeats = 48 observations,
        # comfortably over the analyser's minimum of 2.
        self.assertGreaterEqual(n * 12, 2)

    def test_the_recorded_balance_block_matches_the_glyphs(self):
        self.assertEqual(selection()["balance"], mgs.balance(self.g))


class TestP1Subset(unittest.TestCase):
    def test_the_subset_is_exactly_the_camera_measured_glyphs(self):
        sel = selection()
        self.assertEqual(set(sel["p1_cross_check_subset"]["glyph_keys"]),
                         {g["glyph_key"] for g in sel["glyphs"]})

    def test_the_subset_meets_the_criterion_minimum(self):
        sub = selection()["p1_cross_check_subset"]
        self.assertGreaterEqual(sub["n"], sub["minimum_required"])
        self.assertGreaterEqual(sub["n"], mgs.P1_MIN_GLYPHS)

    def test_the_subset_spans_heights_shapes_and_fonts(self):
        sel = selection()
        keys = set(sel["p1_cross_check_subset"]["glyph_keys"])
        chosen = [g for g in sel["glyphs"] if g["glyph_key"] in keys]
        self.assertEqual({g["nominal_h_mm"] for g in chosen},
                         {float(h) for h in mc.HEIGHTS})
        self.assertEqual({g["glyph_shape"] for g in chosen}, set(mc.SHAPES))
        self.assertEqual(len({g["font"] for g in chosen}), 4)

    def test_a_measured_glyph_left_out_of_the_subset_is_rejected(self):
        sel = selection()
        sel["p1_cross_check_subset"]["glyph_keys"] = \
            sel["p1_cross_check_subset"]["glyph_keys"][:-1]
        issues, _s = check(sel, rederive=False)
        self.assertIn("MEASURED_GLYPH_NOT_CROSS_CHECKED", codes(issues))

    def test_a_subset_below_the_minimum_is_rejected(self):
        sel = selection()
        sel["p1_cross_check_subset"]["glyph_keys"] = \
            sel["p1_cross_check_subset"]["glyph_keys"][:10]
        issues, _s = check(sel, rederive=False)
        self.assertIn("P1_SUBSET_TOO_SMALL", codes(issues))

    def test_a_duplicated_subset_entry_is_rejected(self):
        sel = selection()
        sel["p1_cross_check_subset"]["glyph_keys"].append(
            sel["p1_cross_check_subset"]["glyph_keys"][0])
        issues, _s = check(sel, rederive=False)
        self.assertIn("P1_SUBSET_DUPLICATES", codes(issues))

    def test_a_missing_subset_is_rejected(self):
        sel = selection()
        del sel["p1_cross_check_subset"]
        issues, _s = check(sel, rederive=False)
        self.assertIn("P1_SUBSET_MISSING", codes(issues))


class TestCoverageEnforcement(unittest.TestCase):
    def test_a_selection_missing_a_height_is_rejected(self):
        sel = selection()
        for g in sel["glyphs"]:
            if g["nominal_h_mm"] == 1.2:
                g["nominal_h_mm"] = 2.0
                g["glyph_key"] = "%s:%s:2.00:1" % (g["panel_id"], g["glyph_shape"])
        issues, _s = check(sel, rederive=False)
        self.assertIn("HEIGHT_NOT_COVERED", codes(issues))

    def test_a_selection_with_one_shape_class_is_rejected(self):
        sel = selection()
        for g in sel["glyphs"]:
            if g["shape_class"] == "ROUND":
                g["glyph_shape"], g["shape_class"] = "BAR_I", "FLAT_TOP"
                g["glyph_key"] = "%s:BAR_I:%.2f:1" % (g["panel_id"],
                                                      g["nominal_h_mm"])
        issues, _s = check(sel, rederive=False)
        self.assertIn("SHAPE_CLASS_NOT_COVERED", codes(issues))

    def test_an_empty_p2_class_is_rejected(self):
        sel = selection()
        for g in sel["glyphs"]:
            if g["nominal_h_mm"] == 3.0:
                g["nominal_h_mm"] = 4.0
                g["glyph_key"] = "%s:%s:4.00:1" % (g["panel_id"], g["glyph_shape"])
        issues, _s = check(sel, rederive=False)
        self.assertIn("P2_CLASS_EMPTY", codes(issues))

    def test_a_panel_selected_twice_is_refused_outright(self):
        sel = selection()
        sel["glyphs"].append(dict(sel["glyphs"][0]))
        with self.assertRaises(vs.SelectionError):
            vs.validate(sel, None, glyph_map(), None, None)

    def test_an_empty_selection_is_refused_outright(self):
        with self.assertRaises(vs.SelectionError):
            vs.validate({"glyphs": []}, None, None, None, None)

    def test_a_hand_edited_selection_is_detected_on_rederivation(self):
        sel = selection()
        sel["glyphs"][0]["glyph_shape"] = "H"
        sel["glyphs"][0]["glyph_key"] = "%s:H:%.2f:1" % (
            sel["glyphs"][0]["panel_id"], sel["glyphs"][0]["nominal_h_mm"])
        issues, _s = check(sel)
        self.assertIn("SELECTION_NOT_DERIVED", codes(issues))

    def test_an_inconsistent_key_is_rejected(self):
        sel = selection()
        sel["glyphs"][0]["glyph_key"] = "P01:H:9.00:1"
        issues, _s = check(sel, rederive=False)
        self.assertIn("SELECTION_KEY_INCONSISTENT", codes(issues))

    def test_a_stale_glyph_map_hash_is_rejected(self):
        sel = selection()
        sel["glyph_map_hash"] = "0" * 64
        issues, _s = check(sel, rederive=False)
        self.assertIn("GLYPH_MAP_HASH_MISMATCH", codes(issues))

    def test_validation_is_deterministic(self):
        self.assertEqual(check(), check())


class TestManifestEnforcement(unittest.TestCase):
    def test_a_compliant_manifest_is_accepted(self):
        issues, summary = check(manifest=nominal_runs())
        self.assertEqual(codes(issues), [])
        self.assertEqual(codes(issues, "WARN"), [])
        self.assertEqual(summary["nominal_panels_in_manifest"], 20)

    def test_a_run_measuring_a_different_glyph_is_rejected(self):
        man = nominal_runs()
        man["runs"][0]["glyph_label"] = ("H" if man["runs"][0]["glyph_label"] != "H"
                                        else "T")
        issues, _s = check(manifest=man)
        self.assertIn("RUN_MEASURES_UNSELECTED_GLYPH", codes(issues))

    def test_a_run_measuring_a_different_height_is_rejected(self):
        man = nominal_runs()
        man["runs"][0]["nominal_h_mm"] = 6.0
        issues, _s = check(manifest=man)
        self.assertIn("RUN_MEASURES_UNSELECTED_GLYPH", codes(issues))

    def test_a_panel_with_two_measured_glyphs_is_rejected(self):
        man = nominal_runs()
        extra = dict(man["runs"][0], run_id="extra", glyph_label="RING_O",
                     nominal_h_mm=6.0)
        man["runs"].append(extra)
        issues, _s = check(manifest=man)
        self.assertIn("PANEL_MEASURES_TWO_GLYPHS", codes(issues))
        self.assertIn("RUN_MEASURES_UNSELECTED_GLYPH", codes(issues))

    def test_an_unselected_panel_is_rejected(self):
        man = nominal_runs()
        man["runs"][0]["panel_id"] = "P99"
        issues, _s = check(manifest=man)
        self.assertIn("PANEL_NOT_SELECTED", codes(issues))

    def test_a_missing_selection_hash_is_rejected(self):
        man = nominal_runs()
        del man["selection_hash"]
        issues, _s = check(manifest=man)
        self.assertIn("SELECTION_HASH_MISMATCH", codes(issues))

    def test_a_swapped_selection_hash_is_rejected(self):
        man = nominal_runs()
        man["selection_hash"] = "0" * 64
        issues, _s = check(manifest=man)
        self.assertIn("SELECTION_HASH_MISMATCH", codes(issues))

    def test_a_nominal_run_without_a_panel_is_rejected(self):
        man = nominal_runs()
        man["runs"][0]["panel_id"] = None
        issues, _s = check(manifest=man)
        self.assertIn("RUN_WITHOUT_PANEL", codes(issues))

    def test_stress_runs_are_exempt_from_the_glyph_rule(self):
        man = nominal_runs()
        man["runs"].append({"run_id": "S-BOWED-1", "panel_id": "P01",
                            "glyph_label": "RING_O", "nominal_h_mm": 6.0,
                            "safety_class": "BOWED_PANEL"})
        issues, _s = check(manifest=man)
        self.assertEqual(codes(issues), [])

    def test_panels_without_runs_yet_are_only_a_warning(self):
        man = nominal_runs()
        man["runs"] = man["runs"][:5]
        issues, _s = check(manifest=man)
        self.assertEqual(codes(issues), [])
        self.assertIn("SELECTED_PANEL_HAS_NO_RUNS", codes(issues, "WARN"))


class TestReferenceCrossCheck(unittest.TestCase):
    def test_a_missing_reference_row_is_reported_as_b2_work(self):
        issues, _s = check(reference=[])
        self.assertIn("P1_SUBSET_NOT_IN_REFERENCE_TABLE", codes(issues, "WARN"))
        self.assertEqual(codes(issues), [])

    def test_present_reference_rows_clear_the_warning(self):
        ref = [{"panel_id": g["panel_id"], "glyph_shape": g["glyph_shape"],
                "nominal_h_mm": g["nominal_h_mm"], "glyph_index": 1}
               for g in selection()["glyphs"]]
        issues, _s = check(reference=ref)
        self.assertEqual(codes(issues, "WARN"), [])


class TestCli(unittest.TestCase):
    def setUp(self):
        self.tmp = tempfile.mkdtemp()

    def tearDown(self):
        shutil.rmtree(self.tmp)

    def _cli(self, argv):
        buf = io.StringIO()
        old_o, old_e = sys.stdout, sys.stderr
        sys.stdout, sys.stderr = buf, buf
        try:
            rc = vs.main(argv)
        finally:
            sys.stdout, sys.stderr = old_o, old_e
        return rc, buf.getvalue()

    def test_committed_selection_is_accepted(self):
        rc, txt = self._cli([])
        self.assertEqual(rc, 0)
        self.assertIn("ACCEPTED", txt)

    def test_a_manifest_measuring_the_wrong_glyph_is_rejected(self):
        man = nominal_runs()
        man["runs"][0]["nominal_h_mm"] = 6.0
        p = os.path.join(self.tmp, "m.json")
        dump_json(p, man)
        rc, txt = self._cli(["--manifest", p])
        self.assertEqual(rc, 1)
        self.assertIn("RUN_MEASURES_UNSELECTED_GLYPH", txt)

    def test_unreadable_selection_exits_two(self):
        rc, txt = self._cli(["--selection", os.path.join(self.tmp, "nope.json")])
        self.assertEqual(rc, 2)
        self.assertIn("REJECTED", txt)


if __name__ == "__main__":
    unittest.main(verbosity=2)
